<?php
/**
 * The MIT License (MIT)
 * Copyright (c) 2018 Serhii Popov
 * This source file is subject to The MIT License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 *
 * @category Popov
 * @package Popov_<package>
 * @author Serhii Popov <popow.serhii@gmail.com>
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 */

$form1 = $this->vars('form1');
$form1->setAttribute('action', $this->url('admin/default', [
    'resource' => $this->current('resource'),
    'action' => 'edit',
    'id' => $form1->getObject()->getId(),
    'lang' => $this->current('request')->getAttribute('lang'),
]));

$form2 = $this->vars('form2');
$form2->setAttribute('action', $this->url('admin/default', [
    'resource' => $this->current('resource'),
    'action' => 'edit',
    'id' => $form2->getObject()->getId(),
    'lang' => $this->current('request')->getAttribute('lang'),
]));

$form3 = $this->vars('form3');
$form3->setAttribute('action', $this->url('admin/default', [
    'resource' => $this->current('resource'),
    'action' => 'edit',
    'id' => $form3->getObject()->getId(),
    'lang' => $this->current('request')->getAttribute('lang'),
]));
?>
<script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=5n8uhc6lpsuu8q2ewotgza7nzx5j0osku90zlnwojxmg9296"></script>
<script>tinymce.init(
        {
            selector:'textarea',
            height: 'auto'
        });
</script>
<?= $this->partial('form::form', ['form' => $form1]) ?>
<?= $this->partial('form::form', ['form' => $form2]) ?>
<?= $this->partial('form::form', ['form' => $form3]) ?>
